In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import pandas_datareader.data as web
import os
import re
import requests
import json
from datetime import datetime
import seaborn as sns

In [3]:
# source folder
folder_name = 'Factset_Price_History_Downloads'
terms = [2, 3, 5, 7, 10, 20 , 30 ]

# iterate over the sub folders to access the files
yr_files = { f'{term}yr': os.listdir(f'{folder_name}/us_{term}yr') for term in terms }

all_dfs = {}
all_by_yr = None
for term in terms:
    # start with the first df
    all_by_yr = pd.read_excel(f'{folder_name}/us_{term}yr/' + yr_files[f"{term}yr"][0], skiprows=2)
    all_by_yr.drop(columns = [ 'Composite'], inplace=True)
    all_by_yr.sort_values(by='Date', inplace = True)

    ## concat the rest of the dfs.
    for file in yr_files[f"{term}yr"][1:]:
      df = pd.read_excel(f'{folder_name}/us_{term}yr/{file}', skiprows=2)
      df.dropna(how='all', inplace=True)
      df.sort_values(by='Date', inplace=True)
      df.drop(columns = ['Date', 'Composite'], inplace=True)
      all_by_yr= pd.concat([all_by_yr, df], axis = 1)
      df = None

    all_dfs[f"{term}yr"] = all_by_yr
    all_by_yr = None

In [4]:
# get the CUSIPs
page_size   = 100
page_number = 1
url = 'https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/auctions_query'

def get_treasuries(url, params):
    '''
     Function to pull data CUSIP data from the US Treasury
    '''

    resp=requests.get( url = url, params=params)
    data_dict = json.loads(resp.text)
    if  data_dict.get('data') is None:
      return None
    df = pd.DataFrame(data_dict['data'])
    df.sort_values(by="auction_date", inplace=True)
    return df

def extract_cusip(text):
    '''
     Function to extract the cusip from the column name
    '''
    substr = re.search(r'\((.+)\)',text )
    if substr:
        val= substr.group(1) # Extract the matched substring
        return val

    return None

In [5]:
processed_dfs = {}


for term in terms:
    ## Using 252 and the number of trading days + 20 days as a buffer for any unusual years
    ## Capturing the length of all non-nan values for each CUSIP's Column then recording the index of the column
    length_issues_idxs  = np.argwhere(len(all_dfs[f'{term}yr']) - all_dfs[f'{term}yr'].isna().sum().values > term * 252 + 20  )
    length_issues_idxs  = np.array( [ x[0] for x in length_issues_idxs])
    affected_cusips     = [extract_cusip(t) for t in list(all_dfs[f'{term}yr'].iloc[: , length_issues_idxs[ 1:]].columns)]
    params = { 'fields': 'cusip,security_term,security_type,issue_date,auction_date',
                  'filter': f'cusip:in:({",".join(affected_cusips)})',
                  'page[number]' : f'{page_number}',
                  'page[size]'   : f'{page_size}'
            }


    if len(length_issues_idxs) > 1 :
        issues_df = get_treasuries(url, params)
        issues_df.sort_values(by=['cusip', 'issue_date'])

        #Exclude any CUSIP that started before 2000. We will keep the time series that started after 2000.
        cusips_filter   = issues_df['cusip'][issues_df.issue_date < '2000-01-01']
        affected_cusips = issues_df['cusip'][~issues_df.cusip.isin( cusips_filter)].drop_duplicates().values
        print('Affected Cusips : ', affected_cusips)
        #Save for future reference
        issues_df.to_csv(f'Factset_Price_History_Reused_Cusips/us_treasuries/reused_cusips_{term}yr.csv', index=False)

    #Drop The CUSIP from the shorter length DataFrame

    mask = []
    for i, col  in enumerate(all_dfs[f'{term}yr'].iloc[:, 1:].columns):
      for cusip in affected_cusips:
          if f'({cusip})' in col:
            mask.append(i)
    print('Number of affected cusips:' , len(mask))
    cols_ser = pd.Series(all_dfs[f'{term}yr'].iloc[:, 1:].columns)
    cols_to_drop = cols_ser.iloc[mask].values
    df = all_dfs[f'{term}yr'].drop(columns= cols_to_drop)
    processed_dfs[f'{term}yr'] = df

Affected Cusips :  ['912828ST8' '912828SY7' '912828TM2' '912828TS9' '912828TW0' '912828UR9'
 '912828C57' '912828WG1' '912828F62']
Number of affected cusips: 9
Affected Cusips :  ['912828AN0' '912828TY6' '91282CEU1']
Number of affected cusips: 3
Affected Cusips :  ['912828CZ1' '912828RE2' '912828RH5' '912828M80' '912828N30' '912828W71'
 '912828XT2' '912828Z78']
Number of affected cusips: 8
Number of affected cusips: 0
Number of affected cusips: 0
Affected Cusips :  ['912810FR4']
Number of affected cusips: 1
Number of affected cusips: 0

In [6]:
processed_dfs.keys()

dict_keys(['2yr', '3yr', '5yr', '7yr', '10yr', '20yr', '30yr'])

In [11]:
processed_dfs['2yr']

,Date,United States Treasury Notes 0.25% 30-SEP-2023 (91282CDA6),United States Treasury Notes 0.125% 31-AUG-2023 (91282CCU3),United States Treasury Notes FRN 31-JUL-2023 (91282CCQ2),United States Treasury Notes 0.125% 31-JUL-2023 (91282CCN9),United States Treasury Notes 0.125% 30-JUN-2023 (91282CCK5),United States Treasury Notes 0.125% 31-MAY-2023 (91282CCD1),United States Treasury Notes FRN 30-APR-2023 (91282CBY6),United States Treasury Notes 0.125% 30-APR-2023 (91282CBX8),United States Treasury Notes 0.125% 31-MAR-2023 (91282CBU4),...,Government of the United States of America 5.75% 31-OCT-2002 (9128273L4),Government of the United States of America 6.0% 30-SEP-2002 (9128276L1),Government of the United States of America 6.125% 31-AUG-2002 (9128276K3),Government of the United States of America 6.25% 31-JUL-2002 (9128276H0),Government of the United States of America 6.375% 30-JUN-2002 (9128276F4),Government of the United States of America 6.625% 31-MAY-2002 (9128276E7),Government of the United States of America 6.375% 30-APR-2002 (9128276C1),Government of the United States of America 6.5% 31-MAR-2002 (9128276B3),Government of the United States of America 6.5% 28-FEB-2002 (9128276A5),Government of the United States of America 6.375% 31-JAN-2002 (9128275X6)
0,1999-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6417,2025-07-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6418,2025-07-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6419,2025-07-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6420,2025-07-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6421,2025-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# load the fred data
df_fred = pd.read_parquet("FRED_Data/fred_raw.parquet")
df_fred.head()

,id,title,observation_start,observation_end,frequency,frequency_short,units,units_short,seasonal_adjustment,seasonal_adjustment_short,last_updated,popularity,group_popularity,notes
495,EXPINF1YR,1-Year Expected Inflation,1982-01-01,2025-07-01,Monthly,M,Percent,%,Not Seasonally Adjusted,NSA,2025-07-15 14:33:09-05,65,65,The Federal Reserve Bank of Cleveland estimate...
490,REAINTRATREARAT1YE,1-Year Real Interest Rate,1982-01-01,2025-07-01,Monthly,M,Percent,%,Not Seasonally Adjusted,NSA,2025-07-15 14:33:03-05,65,65,The Federal Reserve Bank of Cleveland estimate...
45,T10YIEM,10-Year Breakeven Inflation Rate,2003-01-01,2025-06-01,Monthly,M,Percent,%,Not Seasonally Adjusted,NSA,2025-07-01 16:01:06-05,47,89,The breakeven inflation rate represents a meas...
419,EXPINF10YR,10-Year Expected Inflation,1982-01-01,2025-07-01,Monthly,M,Percent,%,Not Seasonally Adjusted,NSA,2025-07-15 14:33:10-05,67,67,The Federal Reserve Bank of Cleveland estimate...
107,REAINTRATREARAT10Y,10-Year Real Interest Rate,1982-01-01,2025-07-01,Monthly,M,Percent,%,Not Seasonally Adjusted,NSA,2025-07-15 14:33:03-05,80,80,The Federal Reserve Bank of Cleveland estimate...

In [9]:
symbols = [
    "FEDFUNDS", "DGS10", "T5YIE", "T10YIE", "T10Y3M", "THREEFYTP10", "REAINTRATREARAT10Y", "VIXCLS", "EFFR", "CPILFESL",
    "USEPUINDXD", "GEPUCURRENT", 'DFII10', 'DGS10', 'DTWEXBGS', 'DCOILWTICO', 'DGS2', 'DGS5',
]

fred_series = {
    'T5YIE': '5_Year_Inflation_Expectation',
    'T10YIE': '10_Year_Inflation_Expectation',
    'T10Y3M': '10_Year_3_Year_Spread',
    'FEDFUNDS': 'Fed_Funds_Rate',
    'THREEFYTP10': '10_Year_Term_Premium',
    'REAINTRATREARAT10Y': '10yr_real_intrest',
    'EFFR': 'Effective_Fed_Funds_Rate_Daily',
    'CPILFESL': 'CPI_Core',
    'USEPUINDXD': 'Economic_Policy_Uncertainty_US',
    'GEPUCURRENT': 'Global_EPU_Index',
    'REAINTRATREARAT10Y': 'Real_10-Year_Yield',
    'DFII10': '10_Year_TIPS_Yield',
    'DGS10': '10_Year_Treasury_Yield',
    'DTWEXBGS': 'Dollar_Index',
    'DCOILWTICO': 'Crude_Oil_Price_WTI',
    'DGS2': '2_Year_Treasury_Yield',
    'DGS5': '5_Year_Treasury_Yield',
    'WTISPLC': 'WTI_Spot_price',
    'INDPRO': 'Industrial_Production',
    'IPMAN': 'Manufacturing_Production',
    'CBBTCUSD': 'Bitcoin_spot_price',
    'M2SL': 'Money_supply'

}
df_fred[df_fred['id'].isin(symbols)]

,id,title,observation_start,observation_end,frequency,frequency_short,units,units_short,seasonal_adjustment,seasonal_adjustment_short,last_updated,popularity,group_popularity,notes
107,REAINTRATREARAT10Y,10-Year Real Interest Rate,1982-01-01,2025-07-01,Monthly,M,Percent,%,Not Seasonally Adjusted,NSA,2025-07-15 14:33:03-05,80,80,The Federal Reserve Bank of Cleveland estimate...
215,VIXCLS,CBOE Volatility Index: VIX,1990-01-02,2025-07-23,"Daily, Close",D,Index,Index,Not Seasonally Adjusted,NSA,2025-07-24 08:37:07-05,75,75,VIX measures market expectation of near term v...
76,CPILFESL,Consumer Price Index for All Urban Consumers: ...,1957-01-01,2025-06-01,Monthly,M,Index 1982-1984=100,Index 1982-1984=100,Seasonally Adjusted,SA,2025-07-15 07:40:45-05,82,82,"The ""Consumer Price Index for All Urban Consum..."
165,EFFR,Effective Federal Funds Rate,2000-07-03,2025-07-23,Daily,D,Percent,%,Not Seasonally Adjusted,NSA,2025-07-24 08:01:04-05,77,77,For additional historical federal funds rate d...
2,FEDFUNDS,Federal Funds Effective Rate,1954-07-01,2025-06-01,Monthly,M,Percent,%,Not Seasonally Adjusted,NSA,2025-07-01 15:17:14-05,98,99,Daily Federal Funds Rate from 1928-1954 (http...
420,THREEFYTP10,Term Premium on a 10 Year Zero Coupon Bond,1990-01-02,2025-07-18,Daily,D,Percent,%,Not Seasonally Adjusted,NSA,2025-07-22 14:02:03-05,67,67,Kim and Wright (2005) produced this data by fi...

### 📊 Macroeconomic Indicators and FRED Symbols for U.S. Government Bonds

| **Indicator**                          | **FRED Symbol**         | **Description**                                      |
|---------------------------------------|--------------------------|------------------------------------------------------|
| Fed Funds Effective Rate              | `FEDFUNDS`              | Benchmark short-term interest rate                   |
| 10-Year Treasury Yield                | `DGS10`                 | Long-term yield signal                               |
| 5-Year Breakeven Inflation            | `T5YIE`                 | 5-year inflation expectation                         |
| 10-Year Breakeven Inflation           | `T10YIE`                | 10-year inflation expectation                        |
| Yield Curve Spread (10Y minus 3M)     | `T10Y3M`                | Indicator of growth/inversion                        |
| 10-Year Term Premium                  | `THREEFYTP10`           | Premium over short rates for duration risk           |
| 10-Year Real Interest Rate Estimate   | `REAINTRATREARAT10Y`    | Real rate adjusted for inflation expectations        |

In [10]:
# get the series
# Pull data from FRED and store in a dictionary
start = datetime(1950, 1, 1)
end = datetime(2025, 7, 28)
data = {}
for symbol, label in fred_series.items():
    try:
        data[label] = web.DataReader(symbol, 'fred', start, end)
    except Exception as e:
        print(f"Failed to fetch {label} ({symbol}): {e}")
df_all = pd.concat(data.values(), axis=1)
df_all.columns = data.keys()

In [11]:
df_all.head()

,5_Year_Inflation_Expectation,10_Year_Inflation_Expectation,10_Year_3_Year_Spread,Fed_Funds_Rate,10_Year_Term_Premium,Real_10-Year_Yield,Effective_Fed_Funds_Rate_Daily,CPI_Core,Economic_Policy_Uncertainty_US,Global_EPU_Index,...,10_Year_Treasury_Yield,Dollar_Index,Crude_Oil_Price_WTI,2_Year_Treasury_Yield,5_Year_Treasury_Yield,WTI_Spot_price,Industrial_Production,Manufacturing_Production,Bitcoin_spot_price,Money_supply
DATE,,,,,,,,,,,,,,,,,,,,,
1950-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.57,14.0049,NaN,NaN,NaN
1950-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.57,14.0586,NaN,NaN,NaN
1950-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.57,14.5156,NaN,NaN,NaN
1950-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.57,14.9995,NaN,NaN,NaN
1950-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.57,15.3489,NaN,NaN,NaN

In [12]:
df_all.to_parquet("macro_economical_data.parquet")

In [15]:
for key, value in processed_dfs.items():
    print(f"persisting -> {key}")
    try:
        value.to_parquet(f"{key}.parquet")
    except Exception as e:
        print(f"Failed to persist {key}: {e}")

persisting -> 2yr
persisting -> 3yr
persisting -> 5yr
Failed to persist 5yr: Duplicate column names found: ['Date', 'United States Treasury Notes 1.125% 28-FEB-2021 (912828P87)', 'United States Treasury Notes 1.375% 31-JAN-2021 (912828N89)', 'United States Treasury Notes 1.75% 31-DEC-2020 (912828N48)', 'United States Treasury Notes 1.625% 30-NOV-2020 (912828M98)', 'United States Treasury Notes 1.375% 31-OCT-2020 (912828L99)', 'United States Treasury Notes 1.375% 30-SEP-2020 (912828L65)', 'United States Treasury Notes 1.375% 31-AUG-2020 (912828L32)', 'United States Treasury Notes 1.375% 30-APR-2020 (912828K58)', 'United States Treasury Notes 0.125% 15-APR-2020 (912828K33)', 'United States Treasury Notes 1.375% 31-MAR-2020 (912828J84)', 'United States Treasury Notes 1.375% 29-FEB-2020 (912828J50)', 'United States Treasury Notes 1.375% 31-JUL-2018 (912828VQ0)', 'United States Treasury Notes 1.375% 30-JUN-2018 (912828VK3)', 'United States Treasury Notes 1.0% 31-MAY-2018 (912828VE7)', 'United States Treasury Notes 0.625% 30-APR-2018 (912828UZ1)', 'United States Treasury Notes 0.125% 15-APR-2018 (912828UX6)', 'United States Treasury Notes 0.75% 31-MAR-2018 (912828UU2)', 'United States Treasury Notes 0.75% 28-FEB-2018 (912828UR9)', 'United States Treasury Notes 0.875% 31-JAN-2018 (912828UJ7)', 'United States Treasury Notes 0.75% 31-DEC-2017 (912828UE8)', 'United States Treasury Notes 0.625% 30-NOV-2017 (912828UA6)', 'United States Treasury Notes 0.75% 31-OCT-2017 (912828TW0)', 'United States Treasury Notes 0.625% 30-SEP-2017 (912828TS9)', 'United States Treasury Notes 0.625% 31-AUG-2017 (912828TM2)', 'United States Treasury Notes 0.5% 31-JUL-2017 (912828TG5)', 'United States Treasury Notes 0.75% 30-JUN-2017 (912828TB6)', 'United States Treasury Notes 0.625% 31-MAY-2017 (912828SY7)', 'United States Treasury Notes 0.875% 30-APR-2017 (912828SS0)', 'Government of the United States of America 0.125% 15-APR-2017 (912828SQ4)', 'United States Treasury Notes 1.0% 31-MAR-2017 (912828SM3)', 'United States Treasury Notes 0.875% 28-FEB-2017 (912828SJ0)', 'United States Treasury Notes 0.875% 31-JAN-2017 (912828SC5)', 'United States Treasury Notes 0.875% 31-DEC-2016 (912828RX0)', 'United States Treasury Notes 0.875% 30-NOV-2016 (912828RU6)', 'United States Treasury Notes 1.0% 31-OCT-2016 (912828RM4)', 'United States Treasury Notes 1.0% 30-SEP-2016 (912828RJ1)', 'United States Treasury Notes 1.0% 31-AUG-2016 (912828RF9)', 'United States Treasury Notes 1.5% 31-JUL-2016 (912828QX1)', 'United States Treasury Notes 1.5% 30-JUN-2016 (912828QR4)', 'United States Treasury Notes 1.75% 31-MAY-2016 (912828QP8)', 'United States Treasury Notes 2.0% 30-APR-2016 (912828QF0)', 'Government of the United States of America 0.125% 15-APR-2016 (912828QD5)', 'United States Treasury Notes 2.25% 31-MAR-2016 (912828QA1)', 'United States Treasury Notes 2.125% 29-FEB-2016 (912828QJ2)', 'United States Treasury Notes 2.0% 31-JAN-2016 (912828PS3)', 'United States Treasury Notes 2.125% 31-DEC-2015 (912828PM6)', 'United States Treasury Notes 1.375% 30-NOV-2015 (912828PJ3)', 'United States Treasury Notes 1.25% 31-OCT-2015 (912828PE4)', 'United States Treasury Notes 1.25% 30-SEP-2015 (912828NZ9)', 'United States Treasury Notes 1.25% 31-AUG-2015 (912828NV8)', 'United States Treasury Notes 1.75% 31-JUL-2015 (912828NP1)', 'United States Treasury Notes 1.875% 30-JUN-2015 (912828NL0)', 'United States Treasury Notes 2.125% 31-MAY-2015 (912828NF3)', 'United States Treasury Notes 2.5% 30-APR-2015 (912828MZ0)', 'Government of the United States of America 0.5% 15-APR-2015 (912828MY3)', 'United States Treasury Notes 2.5% 31-MAR-2015 (912828MW7)', 'United States Treasury Notes 2.375% 28-FEB-2015 (912828MR8)', 'United States Treasury Notes 2.25% 31-JAN-2015 (912828MH0)', 'United States Treasury Notes 2.625% 31-DEC-2014 (912828ME7)', 'United States Treasury Notes 2.125% 30-NOV-2014 (912828LZ1)', 'United States Treasury Notes 2.375% 31-OCT-2014 (912828LS7)', 'United States Treasury Notes 1.125% 31-OCT-2026 (91282CDG3)', 'Government of the United States of America 0.125% 15-OCT-2026 (91282CDC2)', 'United States Treasury Notes 0.875% 30-SEP-2026 (91282CCZ2)', 'United States Treasury Notes 0.75% 31-AUG-2026 (91282CCW9)', 'United States Treasury Notes 0.625% 31-JUL-2026 (91282CCP4)', 'United States Treasury Notes 0.875% 30-JUN-2026 (91282CCJ8)', 'United States Treasury Notes 0.75% 31-MAY-2026 (91282CCF6)', 'United States Treasury Notes 0.75% 30-APR-2026 (91282CBW0)', 'Government of the United States of America 0.125% 15-APR-2026 (91282CCA7)', 'United States Treasury Notes 0.75% 31-MAR-2026 (91282CBT7)', 'United States Treasury Notes 0.5% 28-FEB-2026 (91282CBQ3)', 'United States Treasury Notes 0.375% 31-JAN-2026 (91282CBH3)', 'United States Treasury Notes 0.375% 31-DEC-2025 (91282CBC4)', 'United States Treasury Notes 0.375% 30-NOV-2025 (91282CAZ4)', 'United States Treasury Notes 0.25% 31-OCT-2025 (91282CAT8)', 'Government of the United States of America 0.125% 15-OCT-2025 (91282CAQ4)', 'United States Treasury Notes 0.25% 30-SEP-2025 (91282CAM3)', 'United States Treasury Notes 0.25% 31-AUG-2025 (91282CAJ0)', 'United States Treasury Notes 0.25% 31-JUL-2025 (91282CAB7)', 'United States Treasury Notes 0.25% 30-JUN-2025 (912828ZW3)', 'United States Treasury Notes 0.25% 31-MAY-2025 (912828ZT0)', 'United States Treasury Notes 0.375% 30-APR-2025 (912828ZL7)', 'Government of the United States of America 0.125% 15-APR-2025 (912828ZJ2)', 'United States Treasury Notes 0.5% 31-MAR-2025 (912828ZF0)', 'United States Treasury Notes 1.125% 28-FEB-2025 (912828ZC7)', 'United States Treasury Notes 1.375% 31-JAN-2025 (912828Z52)', 'United States Treasury Notes 1.75% 31-DEC-2024 (912828YY0)', 'United States Treasury Notes 1.5% 30-NOV-2024 (912828YV6)', 'United States Treasury Notes 1.5% 31-OCT-2024 (912828YM6)', 'Government of the United States of America 0.125% 15-OCT-2024 (912828YL8)', 'United States Treasury Notes 1.5% 30-SEP-2024 (912828YH7)', 'United States Treasury Notes 1.25% 31-AUG-2024 (912828YE4)', 'United States Treasury Notes 1.75% 31-JUL-2024 (912828Y87)', 'United States Treasury Notes 2.75% 31-JUL-2023 (912828Y61)', 'United States Treasury Notes 1.75% 30-JUN-2022 (912828XW5)', 'United States Treasury Notes 1.75% 31-MAY-2022 (912828XR6)', 'United States Treasury Notes 1.875% 30-APR-2022 (912828X47)', 'United States Treasury Notes 0.125% 15-APR-2022 (912828X39)', 'United States Treasury Notes 1.875% 31-MAR-2022 (912828W89)', 'United States Treasury Notes 1.625% 31-JUL-2020 (912828XM7)', 'United States Treasury Notes 1.625% 30-JUN-2020 (912828XH8)', 'United States Treasury Notes 1.5% 31-MAY-2020 (912828XE5)', 'United States Treasury Notes 1.625% 31-JUL-2019 (912828WW6)', 'United States Treasury Notes 1.625% 30-JUN-2019 (912828WS5)', 'United States Treasury Notes 1.5% 31-MAY-2019 (912828WL0)', 'United States Treasury Notes 1.25% 31-OCT-2018 (912828WD8)', 'United States Treasury Notes 1.875% 28-FEB-2022 (912828W55)', 'United States Treasury Notes 1.875% 31-JAN-2022 (912828V72)', 'United States Treasury Notes 2.0% 31-DEC-2021 (912828U81)', 'United States Treasury Notes 1.75% 30-NOV-2021 (912828U65)', 'United States Treasury Notes 1.25% 31-OCT-2021 (912828T67)', 'United States Treasury Notes 1.125% 30-SEP-2021 (912828T34)', 'United States Treasury Notes 1.125% 31-JUL-2021 (912828S76)', 'United States Treasury Notes 1.125% 30-JUN-2021 (912828S27)', 'United States Treasury Notes 1.375% 31-MAY-2021 (912828R77)', 'United States Treasury Notes 1.375% 30-APR-2021 (912828Q78)', 'United States Treasury Notes 0.125% 15-APR-2021 (912828Q60)', 'United States Treasury Notes 1.25% 31-MAR-2021 (912828Q37)', 'United States Treasury Notes 4.25% 31-JAN-2030 (91282CMG3)', 'Government of the United States of America 4.0% 28-FEB-2030 (91282CMQ1)', 'United States Treasury Notes 4.375% 31-DEC-2029 (91282CMD0)', 'United States Treasury Notes 4.125% 30-NOV-2029 (91282CMA6)', 'United States Treasury Notes 4.125% 31-OCT-2029 (91282CLR0)', 'Government of the United States of America 1.625% 15-OCT-2029 (91282CLV1)', 'United States Treasury Notes 3.5% 30-SEP-2029 (91282CLN9)', 'United States Treasury Notes 3.625% 31-AUG-2029 (91282CLK5)', 'United States Treasury Notes 4.0% 31-JUL-2029 (91282CLC3)', 'United States Treasury Notes 4.25% 30-JUN-2029 (91282CKX8)', 'United States Treasury Notes 4.5% 31-MAY-2029 (91282CKT7)', 'United States Treasury Notes 4.625% 30-APR-2029 (91282CKP5)', 'Government of the United States of America 2.125% 15-APR-2029 (91282CKL4)', 'United States Treasury Notes 4.125% 31-MAR-2029 (91282CKG5)', 'United States Treasury Notes 4.25% 28-FEB-2029 (91282CKD2)', 'United States Treasury Notes 4.0% 31-JAN-2029 (91282CJW2)', 'United States Treasury Notes 3.75% 31-DEC-2028 (91282CJR3)', 'United States Treasury Notes 4.375% 30-NOV-2028 (91282CJN2)', 'United States Treasury Notes 4.875% 31-OCT-2028 (91282CJF9)', 'Government of the United States of America 2.375% 15-OCT-2028 (91282CJH5)', 'United States Treasury Notes 4.625% 30-SEP-2028 (91282CJA0)', 'United States Treasury Notes 4.375% 31-AUG-2028 (91282CHX2)', 'United States Treasury Notes 4.125% 31-JUL-2028 (91282CHQ7)', 'United States Treasury Notes 4.0% 30-JUN-2028 (91282CHK0)', 'United States Treasury Notes 3.625% 31-MAY-2028 (91282CHE4)', 'United States Treasury Notes 3.5% 30-APR-2028 (91282CHA2)', 'Government of the United States of America 1.25% 15-APR-2028 (91282CGW5)', 'United States Treasury Notes 3.625% 31-MAR-2028 (91282CGT2)', 'United States Treasury Notes 4.0% 29-FEB-2028 (91282CGP0)', 'United States Treasury Notes 3.5% 31-JAN-2028 (91282CGH8)', 'United States Treasury Notes 3.875% 31-DEC-2027 (91282CGC9)', 'United States Treasury Notes 3.875% 30-NOV-2027 (91282CFZ9)', 'United States Treasury Notes 4.125% 31-OCT-2027 (91282CFU0)', 'Government of the United States of America 1.625% 15-OCT-2027 (91282CFR7)', 'United States Treasury Notes 4.125% 30-SEP-2027 (91282CFM8)', 'United States Treasury Notes 3.125% 31-AUG-2027 (91282CFH9)', 'United States Treasury Notes 2.75% 31-JUL-2027 (91282CFB2)', 'United States Treasury Notes 3.25% 30-JUN-2027 (91282CEW7)', 'United States Treasury Notes 2.625% 31-MAY-2027 (91282CET4)', 'United States Treasury Notes 2.75% 30-APR-2027 (91282CEN7)', 'Government of the United States of America 0.125% 15-APR-2027 (91282CEJ6)', 'United States Treasury Notes 2.5% 31-MAR-2027 (91282CEF4)', 'United States Treasury Notes 1.875% 28-FEB-2027 (91282CEC1)', 'United States Treasury Notes 1.25% 31-DEC-2026 (91282CDQ1)', 'United States Treasury Notes 1.25% 30-NOV-2026 (91282CDK4)', '91282CMQ1', 'United States Treasury Notes 3.875% 30-JUN-2030 (KWTDTQ-S)', 'United States Treasury Notes 4.0% 31-MAY-2030 (91282CNG2)', 'United States Treasury Notes 3.875% 30-APR-2030 (91282CMZ1)', 'Government of the United States of America 1.625% 15-APR-2030 (91282CNB3)', 'United States Treasury Notes 4.0% 31-MAR-2030 (91282CMU2)', 'United States Treasury Notes 4.0% 28-FEB-2030 (91282CGQ8)', 'Government of the United States of America 4.0% 28-FEB-2030 (91282CMQ1)', 'United States Treasury Notes 3.875% 30-JUN-2030 (91282CNK3)', 'United States Treasury Notes 4.25% 30-SEP-2012 (912828HE3)', 'United States Treasury Notes 4.125% 31-AUG-2012 (912828HC7)', 'United States Treasury Notes 4.625% 31-JUL-2012 (912828GZ7)', 'United States Treasury Notes 4.875% 30-JUN-2012 (912828GW4)', 'United States Treasury Notes 4.75% 31-MAY-2012 (912828GU8)', 'United States Treasury Notes 4.5% 30-APR-2012 (912828GQ7)', 'Government of the United States of America 2.0% 15-APR-2012 (912828GN4)', 'United States Treasury Notes 4.5% 31-MAR-2012 (912828GM6)', 'United States Treasury Notes 4.625% 29-FEB-2012 (912828GK0)', 'United States Treasury Notes 4.75% 31-JAN-2012 (912828GF1)', 'United States Treasury Notes 4.625% 31-DEC-2011 (912828GC8)', 'United States Treasury Notes 4.5% 30-NOV-2011 (912828GA2)', 'Government of the United States of America 4.625% 31-OCT-2011 (912828FW5)', 'Government of the United States of America 4.5% 30-SEP-2011 (912828FU9)', 'Government of the United States of America 4.625% 31-AUG-2011 (912828FS4)', 'Government of the United States of America 4.875% 31-JUL-2011 (912828FN5)', 'Government of the United States of America 5.125% 30-JUN-2011 (912828FK1)', 'Government of the United States of America 4.875% 31-MAY-2011 (912828FH8)', 'Government of the United States of America 4.875% 30-APR-2011 (912828FD7)', 'Government of the United States of America 2.375% 15-APR-2011 (912828FB1)', 'Government of the United States of America 4.75% 31-MAR-2011 (912828FA3)', 'Government of the United States of America 4.5% 28-FEB-2011 (912828EX4)', 'Government of the United States of America 4.25% 15-JAN-2011 (912828ES5)', 'Government of the United States of America 4.375% 15-DEC-2010 (912828EQ9)', 'Government of the United States of America 4.5% 15-NOV-2010 (912828EM8)', 'Government of the United States of America 4.25% 15-OCT-2010 (912828EJ5)', 'Government of the United States of America 3.875% 15-SEP-2010 (912828EG1)', 'Government of the United States of America 4.125% 15-AUG-2010 (912828ED8)', 'Government of the United States of America 3.875% 15-JUL-2010 (912828DZ0)', 'Government of the United States of America 3.625% 15-JUN-2010 (912828DX5)', 'Government of the United States of America 3.875% 15-MAY-2010 (912828DU1)', 'Government of the United States of America 4.0% 15-APR-2010 (912828DR8)', 'Government of the United States of America 4.0% 15-MAR-2010 (912828DP2)', 'Government of the United States of America 3.5% 15-FEB-2010 (912828DL1)', 'Government of the United States of America 3.625% 15-JAN-2010 (912828DG2)', 'Government of the United States of America 3.5% 15-DEC-2009 (912828DE7)', 'Government of the United States of America 3.5% 15-NOV-2009 (912828DB3)', 'Government of the United States of America 3.375% 15-OCT-2009 (912828CX6)', 'Government of the United States of America 3.375% 15-SEP-2009 (912828CV0)', 'Government of the United States of America 3.5% 15-AUG-2009 (912828CS7)', 'Government of the United States of America 3.625% 15-JUL-2009 (912828CN8)', 'Government of the United States of America 4.0% 15-JUN-2009 (912828CL2)', 'Government of the United States of America 3.875% 15-MAY-2009 (912828CH1)', 'Government of the United States of America 3.125% 15-APR-2009 (912828CE8)', 'Government of the United States of America 2.625% 15-MAR-2009 (912828CC2)', 'Government of the United States of America 3.0% 15-FEB-2009 (912828BZ2)', 'Government of the United States of America 3.25% 15-JAN-2009 (912828BV1)', 'Government of the United States of America 3.375% 15-DEC-2008 (912828BT6)', 'Government of the United States of America 3.375% 15-NOV-2008 (912828BQ2)', 'Government of the United States of America 3.125% 15-OCT-2008 (912828BM1)', 'Government of the United States of America 3.125% 15-SEP-2008 (912828BK5)', 'Government of the United States of America 3.25% 15-AUG-2008 (912828BG4)', 'Government of the United States of America 2.625% 15-MAY-2008 (912828AZ3)', 'Government of the United States of America 3.0% 15-FEB-2008 (912828AT7)', 'Government of the United States of America 3.0% 15-NOV-2007 (912828AN0)', 'Government of the United States of America 3.25% 15-AUG-2007 (912828AH3)', 'Government of the United States of America 4.375% 15-MAY-2007 (912828AC4)', 'Government of the United States of America 3.5% 15-NOV-2006 (9128277F3)', 'Government of the United States of America 4.625% 15-MAY-2006 (9128276X5)', 'Government of the United States of America 5.75% 15-NOV-2005 (9128276N7)', 'Government of the United States of America 6.75% 15-MAY-2005 (9128276D9)', 'United States Treasury Notes 4.25% 15-MAY-2035 (91282CNC)', 'United States Treasury Notes 2.375% 31-OCT-2014 (912828LS7)', 'United States Treasury Notes 2.375% 30-SEP-2014 (912828LQ1)', 'United States Treasury Notes 2.375% 31-AUG-2014 (912828LK4)', 'United States Treasury Notes 2.625% 31-JUL-2014 (912828LC2)', 'United States Treasury Notes 2.625% 30-JUN-2014 (912828KY5)', 'United States Treasury Notes 2.25% 31-MAY-2014 (912828KV1)', 'United States Treasury Notes 1.875% 30-APR-2014 (912828KN9)', 'Government of the United States of America 1.25% 15-APR-2014 (912828KM1)', 'United States Treasury Notes 1.75% 31-MAR-2014 (912828KJ8)', 'United States Treasury Notes 1.875% 28-FEB-2014 (912828KF6)', 'United States Treasury Notes 1.75% 31-JAN-2014 (912828JZ4)', 'United States Treasury Notes 1.5% 31-DEC-2013 (912828JW1)', 'United States Treasury Notes 2.0% 30-NOV-2013 (912828JT8)', 'United States Treasury Notes 2.75% 31-OCT-2013 (912828JQ4)', 'United States Treasury Notes 3.125% 30-SEP-2013 (912828JM3)', 'United States Treasury Notes 3.125% 31-AUG-2013 (912828JK7)', 'United States Treasury Notes 3.375% 31-JUL-2013 (912828JG6)', 'United States Treasury Notes 3.375% 30-JUN-2013 (912828JD3)', 'United States Treasury Notes 3.5% 31-MAY-2013 (912828JB7)', 'United States Treasury Notes 3.125% 30-APR-2013 (912828HY9)', 'Government of the United States of America 0.625% 15-APR-2013 (912828HW3)', 'United States Treasury Notes 2.5% 31-MAR-2013 (912828HV5)', 'United States Treasury Notes 2.75% 28-FEB-2013 (912828HT0)', 'United States Treasury Notes 2.875% 31-JAN-2013 (912828HQ6)', 'United States Treasury Notes 1.75% 30-JUN-2024 (9128286Z8)', 'United States Treasury Notes 2.25% 30-APR-2024 (9128286R6)', 'United States Treasury Notes 0.5% 15-APR-2024 (9128286N5)', 'United States Treasury Notes 2.375% 29-FEB-2024 (9128286G0)', 'United States Treasury Notes 2.5% 31-JAN-2024 (9128285Z9)', 'United States Treasury Notes 2.625% 31-DEC-2023 (9128285U0)', 'United States Treasury Notes 2.875% 30-NOV-2023 (9128285P1)', 'United States Treasury Notes 2.875% 31-OCT-2023 (9128285K2)', 'United States Treasury Notes 2.875% 30-SEP-2023 (9128285D8)', 'United States Treasury Notes 2.75% 31-AUG-2023 (9128284X5)', 'United States Treasury Notes 2.625% 30-JUN-2023 (9128284U1)', 'United States Treasury Notes 2.75% 31-MAY-2023 (9128284S6)', 'United States Treasury Notes 2.75% 30-APR-2023 (9128284L1)', 'United States Treasury Notes 0.625% 15-APR-2023 (9128284H0)', 'United States Treasury Notes 2.5% 31-MAR-2023 (9128284D9)', 'United States Treasury Notes 2.625% 28-FEB-2023 (9128284A5)', 'United States Treasury Notes 2.375% 31-JAN-2023 (9128283U2)', 'United States Treasury Notes 2.0% 31-OCT-2022 (9128283C2)', 'United States Treasury Notes 1.875% 30-SEP-2022 (9128282W9)', 'United States Treasury Notes 1.625% 31-AUG-2022 (9128282S8)', 'United States Treasury Notes 1.875% 31-JUL-2022 (9128282P4)', 'United States Treasury Notes 1.125% 31-AUG-2021 (9128282F6)', 'United States Treasury Notes 1.25% 31-JAN-2020 (912828H52)', 'United States Treasury Notes 1.625% 31-DEC-2019 (912828G95)', 'United States Treasury Notes 1.5% 30-NOV-2019 (912828G61)', 'United States Treasury Notes 1.5% 31-OCT-2019 (912828F62)', 'United States Treasury Notes 1.75% 30-SEP-2019 (912828F39)', 'United States Treasury Notes 1.625% 31-AUG-2019 (912828D80)', 'United States Treasury Notes 1.625% 30-APR-2019 (912828D23)', 'United States Treasury Notes 0.125% 15-APR-2019 (912828C99)', 'United States Treasury Notes 1.625% 31-MAR-2019 (912828C65)', 'United States Treasury Notes 1.5% 28-FEB-2019 (912828C24)', 'United States Treasury Notes 1.5% 31-JAN-2019 (912828B33)', 'United States Treasury Notes 1.5% 31-DEC-2018 (912828A75)', 'United States Treasury Notes 1.25% 30-NOV-2018 (912828A34)', 'United States Treasury Notes 3.625% 31-DEC-2012 (912828HM5)', 'United States Treasury Notes 3.375% 30-NOV-2012 (912828HK9)', 'United States Treasury Notes 3.875% 31-OCT-2012 (912828HG8)']
persisting -> 7yr